---
- name: Check golang installed
  command: which go
  register: go_installed
  ignore_errors: yes

- name: Download and unarchive golang
  become: true
  unarchive:
    src: https://dl.google.com/go/go1.11.linux-amd64.tar.gz
    remote_src: yes
    dest: /usr/local
  when: go_installed.rc != 0

- name: Setup golang environment
  blockinfile:
    path: "~/.bashrc"
    block: |
      export GOROOT=/usr/local/go
      export GOPATH=$HOME/go
      export GO111MODULE=on
      export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

- name: Fix GOPATH owner
  become: yes
  command: chown -R vagrant:vagrant /home/vagrant/go
