---
- name: Add golang apt-repository
  apt_repository:
    repo: ppa:gophers/archive
    state: present

- name: Update apt
  apt: name=golang-1.10 update_cache=yes

- name: Set up PATH
  lineinfile:
    path: "~/.bashrc"
    line: "export PATH=\"/usr/lib/go-1.10/bin:$PATH\""
