---
- name: Add apt repository
  apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present

- name: Install neovim
  apt: name=neovim

- name: Create nvim directories
  file:
    path: "{{ item }}"
    recurse: yes
    state: directory
  loop: 
    - "~/.local/share/nvim/site/autoload/"
    - "~/.config/nvim/"

- name: Install vim-plug
  get_url:
    dest: "~/.local/share/nvim/site/autoload/plug.vim"
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    force: yes

- name: Add init.vim config
  copy:
    dest: "~/.config/nvim/init.vim"
    src: files/nvim/init.vim