---
- name: Check pip installed
  command: which pip
  register: pip_installed
  ignore_errors: yes

- name: Install pip
  become: true
  shell: "curl https://bootstrap.pypa.io/get-pip.py | python"
  when: pip_installed.rc != 0
