---
- hosts: all
  tasks:
    - include_tasks:
        file: tasks/packages.yml
        apply:
          become: true

    - include: tasks/pip.yml

    - include_tasks:
        file: tasks/docker.yml
        apply:
          become: true

    - include: tasks/golang.yml
    - include: tasks/nvim.yml

    - include: tasks/rust.yml
    - include: tasks/vim.yml
    - include: tasks/git.yml
